-- Seed Fomora with a few well-known AI launches so the Radar isn't empty before the crawler runs.
-- Run this AFTER 001_initial_schema.sql in Supabase SQL Editor.

insert into launches (url, name, source, category, description, velocity, signal_badge, base_momentum)
values
  ('https://anthropic.com/news/claude-code',
   'Claude Code',
   'Anthropic',
   'AI Coding',
   'Agentic command-line coding tool that lives in your terminal.',
   'Exploding',
   'Paradigm Shift',
   95),

  ('https://modelcontextprotocol.io',
   'Model Context Protocol (MCP)',
   'Anthropic',
   'AI Infra',
   'Open standard for connecting AI assistants to tools and data sources.',
   'Exploding',
   'Paradigm Shift',
   97),

  ('https://cursor.com/changelog',
   'Cursor 1.0',
   'Cursor',
   'AI Coding',
   'AI-first code editor reaches 1.0 with multi-agent workflows.',
   'Exploding',
   'High Signal',
   90),

  ('https://browser.computer',
   'Comet Browser',
   'Browser Co.',
   'AI Agents',
   'AI-native browser with a built-in agent framework.',
   'Heating up',
   'High Signal',
   85),

  ('https://manus.im',
   'Manus 2',
   'Manus',
   'AI Agents',
   'General-purpose autonomous agent platform.',
   'Heating up',
   'Emerging',
   80),

  ('https://granola.ai',
   'Granola',
   'Granola',
   'AI Productivity',
   'AI meeting notes that run on-device — no bot joins your call.',
   'Steady',
   'High Signal',
   75),

  ('https://perplexity.ai/comet',
   'Perplexity Comet',
   'Perplexity',
   'AI Search',
   'AI search built into any browser tab.',
   'Steady',
   'Emerging',
   72),

  ('https://figma.com/make',
   'Figma Make',
   'Figma',
   'AI Design',
   'Prompt-to-prototype generation inside Figma.',
   'Heating up',
   'High Signal',
   78),

  ('https://mistral.ai/news/mistral-large-3',
   'Mistral Large 3',
   'Mistral',
   'AI Infra',
   'Open-weights frontier model release.',
   'Steady',
   'High Signal',
   82),

  ('https://runwayml.com/gen-4',
   'Runway Gen-4',
   'Runway',
   'Video AI',
   'Cinematic AI video generation, fourth generation.',
   'Steady',
   'Hype',
   60)
on conflict (url) do nothing;
